# Generated by Django 4.0.4 on 2022-05-27 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0002_post_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='doujins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='hentai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='manhua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='manhwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('author', models.CharField(max_length=225)),
                ('summary', models.TextField()),
                ('story', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weebs.anime')),
                ('doujins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weebs.doujins')),
                ('hentai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weebs.hentai')),
                ('manhua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weebs.manhua')),
                ('manhwa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weebs.manhwa')),
            ],
        ),
    ]
