# Generated by Django 4.0.4 on 2022-05-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0003_anime_doujins_hentai_manhua_manhwa_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='summary',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='doujins',
            old_name='summary',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='hentai',
            old_name='summary',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='manhua',
            old_name='summary',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='manhwa',
            old_name='summary',
            new_name='about',
        ),
    ]
