# Generated by Django 4.0.4 on 2022-05-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0004_rename_summary_anime_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doujins',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hentai',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manhua',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manhwa',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
