# Generated by Django 4.0.4 on 2022-05-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0005_anime_episodes_doujins_chapters_hentai_chapters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watching',
            field=models.ManyToManyField(null=True, to='weebs.manhwa'),
        ),
    ]
