# Generated by Django 4.0.4 on 2022-05-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0009_post_type_manhwapost_manhuapost_hentaipost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='author',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='doujins',
            name='author',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='hentai',
            name='author',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='manhua',
            name='author',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='author',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
