# Generated by Django 4.0.4 on 2022-05-31 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0011_alter_post_type_delete_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doujinspost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='doujinspost',
            name='watching',
        ),
        migrations.RemoveField(
            model_name='hentaipost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='hentaipost',
            name='watching',
        ),
        migrations.RemoveField(
            model_name='manhuapost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='manhuapost',
            name='watching',
        ),
        migrations.RemoveField(
            model_name='manhwapost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='manhwapost',
            name='watching',
        ),
        migrations.DeleteModel(
            name='AnimePost',
        ),
        migrations.DeleteModel(
            name='DoujinsPost',
        ),
        migrations.DeleteModel(
            name='HentaiPost',
        ),
        migrations.DeleteModel(
            name='ManhuaPost',
        ),
        migrations.DeleteModel(
            name='ManhwaPost',
        ),
    ]
