# Generated by Django 4.0.4 on 2022-05-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0013_alter_anime_about_alter_doujins_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='watching',
            new_name='manhwa',
        ),
        migrations.AddField(
            model_name='post',
            name='manhua',
            field=models.ManyToManyField(to='weebs.manhua'),
        ),
    ]
