# Generated by Django 4.0.4 on 2022-05-31 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0014_rename_watching_post_manhwa_post_manhua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='manhua',
            field=models.ManyToManyField(blank=True, to='weebs.manhua'),
        ),
        migrations.AlterField(
            model_name='post',
            name='manhwa',
            field=models.ManyToManyField(blank=True, null=True, to='weebs.manhwa'),
        ),
    ]
