# Generated by Django 4.0.4 on 2022-06-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0015_alter_post_manhua_alter_post_manhwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
