# Generated by Django 4.0.4 on 2022-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0016_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='manhwa',
            field=models.ManyToManyField(blank=True, to='weebs.manhwa'),
        ),
    ]
