# Generated by Django 4.0.4 on 2022-06-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weebs', '0017_post_poster_image_alter_post_manhwa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='poster_image',
            new_name='poster_image_lg',
        ),
        migrations.AddField(
            model_name='post',
            name='poster_image_md',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='poster_image_sm',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
