# Generated by Django 4.0.4 on 2022-06-02 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weebs', '0019_post_poster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManhwaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('body', models.TextField(blank=True, null=True)),
                ('poster_image_lg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='images/Poster')),
                ('poster_image_md', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('poster_image_sm', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_on', models.DateTimeField(null=True)),
                ('Type', models.CharField(blank=True, max_length=45, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manhua', models.ManyToManyField(blank=True, to='weebs.manhua')),
                ('manhwa', models.ManyToManyField(blank=True, to='weebs.manhwa')),
            ],
        ),
    ]
